spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapping/*.xml


logging:
  level:
    root: debug